version: '3.8'

services:

  postgres:
    image: docker.arvancloud.ir/library/postgres:15-alpine
    container_name: messaging_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres-events:
    image: docker.arvancloud.ir/library/postgres:15-alpine
    container_name: messageing_events_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_events_data:/var/lib/postgresql/data
    networks:
      - app-network

  kafka:
    image: docker.arvancloud.ir/bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes

    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - app-network

  kafka-ui:
    image: docker.arvancloud.ir/provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

#  migrate:
#    build: .
#    command: ./migrate
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#      - postgres-events
#
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - migrate
#      - kafka

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_events_data:
  kafka_data:
